### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hitesh83** [bmoren/node-omxplayer-sync#3]
installed using install script, tried playing mp4 via command.

 `sudo node omx-sync.js /home/pi/media/test.mp4`

```
/home/pi/node-omxplayer-sync/omx-sync.js:24
var killall = exec('killall omxplayer.bin', (error, stdout, stderr) => {
                                                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```

**Comment by bmoren** [comment]
what version of node are / were you using?
